<?php

/**
 * @file
 * YSE Connect Requester module hooks.
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function yse_connectrequester_theme(): array {
  return [
    'yse_connectrequester_events' => [
      'variables' => [
        'email_audience' => 'YSE',
        'admin_header_bg_color' => '',
        'footer_because' => ' you are a member of the YSE community.',
        'listings' => [],
        'listings_for_audience' => [],
      ],
      'template' => 'yse-connectrequester-events',
    ],
    'html__yse_connectrequester' => [
      'template' => 'html--yse-connectrequester',
      'base hook' => 'html',
    ],
    'page__yse_connectrequester' => [
      'template' => 'page--yse-connectrequester',
      'base hook' => 'page',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_html_alter().
 */
function yse_connectrequester_theme_suggestions_html_alter(array &$suggestions, array $variables): void {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if (str_starts_with($route_name, 'yse_connectrequester.preview')) {
    $suggestions[] = 'html__yse_connectrequester';
  }
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function yse_connectrequester_theme_suggestions_page_alter(array &$suggestions, array $variables): void {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if (str_starts_with($route_name, 'yse_connectrequester.preview')) {
    $suggestions[] = 'page__yse_connectrequester';
  }
}
